### ISSUE TITLE
उदात्तस्वरितयोर्यणः स्वरितोऽनुदात्तस्य (८.२.४)

### ISSUE THREAD

**Issue by ujjvlh** [sandhiH/sa-rules#1]
@vvasuki [सूत्र॑मि॒दं (8.2.4)](https://ashtadhyayi.github.io/suutra/8.2/8.2.4/) विस्मृ॑तं वा प्रामा॒दात्? अथ॒ किञ्चि॑द॒हं स॒म्यङ्नाव॒गच्छा॑मि?

[ashtadhyayi.github.io](https://ashtadhyayi.github.io) अ॒स्मिन् स॒र्वत्रै॒वं प॑श्यामि प्रथमसूत्रव्या॒ख्यां यथा॒धो निर्दि॑ष्टे दृ॒श्यते॑।

[i.imgur.com/IRPSamr.png](https://i.imgur.com/IRPSamr.png)

**Comment by vvasuki** [comment]
> @vvasuki [सूत्र॑मि॒दं (8.2.4)](https://ashtadhyayi.github.io/suutra/8.2/8.2.4/) विस्मृ॑तं वा प्रामा॒दात्? अथ॒ किञ्चि॑द॒हं स॒म्यङ्नाव॒गच्छा॑मि?

आह्! विस्मृतम् एवासीत् तत्। पुनः परीक्षताम् - सम्यग् अस्त्य् अधुना?

> 
> [ashtadhyayi.github.io](https://ashtadhyayi.github.io) अ॒स्मिन् स॒र्वत्रै॒वं प॑श्यामि प्रथमसूत्रव्या॒ख्यां यथा॒धो निर्दि॑ष्टे दृ॒श्यते॑।

परिहृतो दोषः।

**Comment by ujjvlh** [comment]
> आह्! विस्मृतम् एवासीत् तत्। पुनः परीक्षताम् - सम्यग् अस्त्य् अधुना?

स॒म्यगि॑वास्ति। `([\꣡\꣢᳡]?` अत्र॑ प्रश्नचि॒ह्नं न स्या॒त् खलु॑? स॒ञ्चि॒का॒ना॒मानि॒ शुद्धि॒मपे॑क्षन्ते। अस्था॑नयो॒र्हि `non-u-s` इति॑ लिखि॒तं दृ॒श्यते॑।

`$3$7` इत्य॒स्य स्व॑रचिह्नयो॒गस्य॑ प॒श्चात् सं॒स्कर॑णं चिकी॒र्षुः प्रति॑भाति॒ भवा॑न्। अत्रे॒यं मे॑ मनी॒षा-। स्व॒र॒व्य॒व॒सा॒यो३॒॑न्येभ्यः॑ सन्धिनिय॒मेभ्यः॑ पृ॒थक्क्रि॑यताम्। क॒थं तत्? `i__ach.toml` इत्यत्रै॒वं लि॑खतु-

```toml
input_pattern = "([इई])(ँ?)([ACCENTS]?)([OTHER_MARKERS.ALL]*)([PRATYAHARA.ACH])(ँ?)([ACCENTS]?)([OTHER_MARKERS.ALL]*)"
[[substitutions]]
pattern = "य्$5$2$6<yaNsvaraH><prathamaH>$3<dvitIyaH>$7<iti_yaNsvaraH>$4$8"
```

ततः॑ `accent/yaN-u-s__a.toml` इत्यत्र॑-

```toml
input_pattern = "<yaNsvaraH><prathamaH>[\꣡\꣢᳡]<dvitIyaH><itiyaNsvaraH>"
[[substitutions]]
pattern = "\॑"
```

`accent/yaN-u-s__u-s.toml` इत्यत्र॑-

```toml
input_pattern = "<yaNsvaraH><prathamaH>[\꣡\꣢᳡]<dvitIyaH>[\꣡\꣢᳡]<itiyaNsvaraH>"
[[substitutions]]
pattern = "\꣡"
```

`accent/yaN-a__a-u-s.toml` इत्यत्र॑-

```toml
input_pattern = "<yaNsvaraH><prathamaH><dvitIyaH>([ACCENTS]?)<itiyaNsvaraH>"
[[substitutions]]
pattern = "$1"
```

अ॒न्यत्र॑ दीर्घगुणवृद्धिस॒न्धिषु॑ `<ekAdeSasvaraH>` इत्ये॒वं किञ्चि॑ल्लिख्यताम्।

ए॒वं ल॑घु॒त्वं सा॑ध्यते।

**Comment by vvasuki** [comment]
न꣡माम्य् आर्य! सूचन꣡योपकृतो꣡ऽस्मि! भवत्सूचनासारं गृहीत्वा पर्यवर्तयम्। परीक्षताम्। अधुना "priority" सङ्ख्याऽपि नियमानां स्थापिता। भवतोक्ते accent/yaN-u-s__u-s.toml इति नियमे मम सन्देहः - किम् अत्र प्रमाणम्? अयण्-स्वरेष्व् अप्य् एवम् - अथवात्र कश्चन विशेषः?

**Comment by ujjvlh** [comment]
> अधुना "priority" सङ्ख्याऽपि नियमानां स्थापिता।

अपि॑ स॒त्यम् अप॑रिहार्ये॒यम्? क॒थं च॒ तत्र॒ भव॑ता लिखि॒तयोः॑ सं॒ख्ययो॑र्व्यत्य॒यमि॑व पश्यामि? स्व॒र॒व्य॒व॒सा॒यः प॒श्चात् का॒र्यः१॒॑ खलु॑?

>भवतोक्ते accent/yaN-u-s__u-s.toml इति नियमे मम सन्देहः - किम् अत्र प्रमाणम्?

यु॒क्तः स॑न्दे॒हः। न दृ॒ष्टः स्व॑रि॒ताजा॑दिः ~~स्वरि॒तेग॑न्तो वा॒~~ **EDITED** कोऽपि॒ शब्दः॑। तथापि॑ परस्व॒र ए॒व विधी॑यता॒मत्रापि॑। स शो॑भ॒नो भ॑वेत् पाणिन्यविरु॒द्धः।

```toml
input_pattern = "(#ACCENT.YAN[#ACCENT.ALL])([#ACCENT.UDATTA#ACCENT.SVARITA]?)"

[[substitutions]]

pattern = "$2"
```
